### ISSUE TITLE
Normalization in visualizeMosaicResponseSequence

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/IBIOColorDetect#3]
Something is wrong with the frame-to-frame normzlization in visualizeMosaicResponseSequence.  We want this to be constant across the movie.  But it is not.  See t_coneIsomerizationsMovieSpot for an instance where this fails.  The spot is changing in intensity while everything else is constant, but the movie makes it look like the background is changing.  This is because each frame is being normalized to the spot, which is always the most intense region of the image.

**Comment by npcottaris** [comment]
In which branch is t_coneIsomerizationsMovieSpot located? Is it committed?

**Comment by DavidBrainard** [comment]
spots branch, it is now committed and pushed.

**Comment by npcottaris** [comment]
```
>> tbUse('IBIOColorDetect')
>> t_coneIsomerizationsMovieSpot
Computing scene 1 of 51, time -0.417, windowVal 0.002
Undefined function or variable 'Circle'.

Error in drawSpot (line 53)
croppedSpot = Circle(spotRadiusPixels);
```

Is Circle() committed and pushed?
Where is it located?

**Comment by npcottaris** [comment]
The problem was in visualizeSceneOrOpticalImageSequence, not in visualizeMosaicResponseSequence.
I was getting the RGB rendition as

```
rgbFrame = sceneGet(sceneOrOpticalImageSequence{iFrame}, 'rgb image');
```

which normalizes each image for display.

I am now using Matlab's xyz2rgb on the XYZ component of the scene as follows

```
rgbFrame = xyz2rgb(sceneGet(sceneOrOpticalImageSequence{iFrame}, 'xyz'));
```

to avoid this frame-to-frame normalization.
