### ISSUE TITLE
Wiki Installation page for IBIOColorDetect

### ISSUE THREAD

**Issue by RBachy** [isetbio/IBIOColorDetect#9]
This is a quick test to see if I am pointing found issues the right way

"Rename the template file IBIOColorDetect.m, and edit" should be "....IBIOColorDetectLocalHook.m, ..."
"tbUse('IBIOColorDetect');" should be "tbUseProject('IBIOColorDetect');"

**Comment by npcottaris** [comment]
That's good. Label it as an enhancement.

**Comment by npcottaris** [comment]
Updated wiki installation page. Closing this issue.
